### ISSUE TITLE
Error installing pychromecast 9.1.1

### ISSUE THREAD

**Issue by jejo86** [Cygn/pulseaudio-dlna#19]
I tried to follow [this guide on how to install pulseaudio-dlna](https://www.linuxuprising.com/2020/10/how-to-use-pulseaudio-dlna-to-stream.html), but i receive the following error:
 
```
ERROR: pychromecast 9.1.1 has requirement zeroconf>=0.25.1, but you'll have zeroconf 0.24.4 which is incompatible.
```
Could you please ship an installer, with all dependencies included so that this won't be an issue?

**Comment by Cygn** [comment]
I provide a compatible pychromecast at my [COPR](https://copr.fedorainfracloud.org/coprs/cygn/pulseaudio-dlna/packages/), compiled from [here](https://github.com/Cygn/pychromecast). 
Sorry but I don't do debs, this is fedora-packaging focused fork. There are some other packagers looking into this, check at  the upstream, please. 

Alternatively, you can install pychromecast with pip, instead of pulling from your dist-repos. Beware that pulseaudio-dlna is not yet tested with pychromecast, so if yo take this route, let us know if it's OK.

**Comment by jejo86** [comment]
Thanks for the quick response. I noticed it is actually not a problem. Even though I receive this error, streaming the audio to my device does work using `MyDevice (Chromecast)` as well as `MyDevice (DLNA)`.

I only noticed that with Chromecast I get a very long lag. Playing the next song, changing volume, etc. takes around 20sec to take effect, whereas with DLNA this works within 2sec. But that is a different topic...
